// ─── NLF Decision Tree Data Model ─────────────────────────────────────────
// All blocks, questions, options, legislations and routing rules.

const BLOCKS = [
  { id: 'A', label: 'Identidad del Producto', icon: '📦' },
  { id: 'B', label: 'Electrónica y Conectividad', icon: '⚡' },
  { id: 'C', label: 'Mecánica y Presión', icon: '⚙️' },
  { id: 'D', label: 'Elevación y Transporte', icon: '🏗️' },
  { id: 'E', label: 'Equipos de Protección', icon: '🛡️' },
  { id: 'F', label: 'Explosivos y ATEX', icon: '💥' },
  { id: 'G', label: 'Vehículos y Embarcaciones', icon: '🚢' },
  { id: 'H', label: 'Dispositivos Médicos', icon: '🏥' },
  { id: 'I', label: 'Instrumentos de Medida', icon: '📏' },
  { id: 'J', label: 'Sostenibilidad y Packaging', icon: '♻️' },
  { id: 'K', label: 'Productos de Construcción', icon: '🏛️' },
];

// type: 'single' | 'multi' | 'info'
// visibleWhen: null (always) or function(flags) => boolean
// options: [{ value, label, flags: string[] }]
const QUESTIONS = [
  // ── BLOCK A ──────────────────────────────────────────────
  {
    id: 'A.1', block: 'A', type: 'multi',
    label: '¿Qué tipo de producto es? (seleccione todos los que apliquen)',
    visibleWhen: null,
    options: [
      { value: 'consumer_product', label: 'Producto de consumo general', flags: ['A.1.consumer_product'] },
      { value: 'toy_children', label: 'Juguete / producto infantil', flags: ['A.1.toy_children'] },
      { value: 'industrial_professional', label: 'Producto industrial / profesional', flags: ['A.1.industrial_professional'] },
      { value: 'medical', label: 'Dispositivo médico o sanitario', flags: ['A.1.medical'] },
      { value: 'construction', label: 'Producto de construcción', flags: ['A.1.construction'] },
      { value: 'explosive_pyro', label: 'Explosivo / pirotécnico', flags: ['A.1.explosive_pyro'] },
      { value: 'fertiliser_biostimulant', label: 'Fertilizante / bioestimulante', flags: ['A.1.fertiliser_biostimulant'] },
    ],
  },
  {
    id: 'A.1.a', block: 'A', type: 'single',
    label: '¿El producto tiene valor de juego para niños menores de 14 años?',
    visibleWhen: (flags) => flags.has('A.1.toy_children'),
    options: [
      { value: 'yes_play_value', label: 'Sí, tiene valor de juego', flags: ['A.1.a.yes_play_value'] },
      { value: 'no_no_play_value', label: 'No, sin valor de juego', flags: ['A.1.a.no_no_play_value'] },
    ],
  },
  {
    id: 'A.2', block: 'A', type: 'single',
    label: '¿El producto es un artículo completo o un componente?',
    visibleWhen: null,
    options: [
      { value: 'complete', label: 'Producto completo (standalone)', flags: ['A.2.complete_standalone_product'] },
      { value: 'component', label: 'Componente / subconjunto', flags: ['A.2.component'] },
      { value: 'accessory', label: 'Accesorio de otro producto', flags: ['A.2.accessory'] },
    ],
  },
  {
    id: 'A.3', block: 'A', type: 'single',
    label: '¿El producto está destinado exclusivamente a uso militar, policial o espacial?',
    visibleWhen: null,
    options: [
      { value: 'no_military', label: 'No — uso civil', flags: ['A.3.no_military'] },
      { value: 'military_exclusive', label: 'Sí — exclusivamente militar/policial', flags: ['A.3.military_exclusive'] },
      { value: 'space_exclusive', label: 'Sí — exclusivamente espacial', flags: ['A.3.space_exclusive'] },
    ],
  },
  {
    id: 'A.4', block: 'A', type: 'single',
    label: '¿El producto se comercializará en el mercado EU/EEA?',
    visibleWhen: null,
    options: [
      { value: 'eu_eea', label: 'Sí — mercado EU/EEA', flags: ['A.4.eu_eea'] },
      { value: 'outside_eu', label: 'No — exclusivamente fuera de EU', flags: ['A.4.exclusively_outside_eu'] },
    ],
  },

  // ── BLOCK B ──────────────────────────────────────────────
  {
    id: 'B.1', block: 'B', type: 'single',
    label: '¿El producto contiene componentes electrónicos o eléctricos?',
    visibleWhen: null,
    options: [
      { value: 'yes', label: 'Sí', flags: ['B.1.yes'] },
      { value: 'no', label: 'No', flags: ['B.1.no'] },
    ],
  },
  {
    id: 'B.2', block: 'B', type: 'single',
    label: '¿Cuál es el rango de tensión de operación?',
    visibleWhen: (flags) => flags.has('B.1.yes'),
    options: [
      { value: 'below_50ac_75dc', label: '< 50V AC / 75V DC (baja tensión extra)', flags: ['B.2.voltage_below_50ac_75dc'] },
      { value: '50_1000_ac', label: '50–1000V AC', flags: ['B.2.voltage_50_1000_ac'] },
      { value: '75_1500_dc', label: '75–1500V DC', flags: ['B.2.voltage_75_1500_dc'] },
      { value: 'mains_230', label: 'Alimentación de red 230V AC', flags: ['B.2.voltage_mains_230'] },
      { value: 'mains_400', label: 'Alimentación de red 400V AC', flags: ['B.2.voltage_mains_400'] },
      { value: 'battery_above_75dc', label: 'Batería > 75V DC', flags: ['B.2.voltage_battery_above_75dc'] },
      { value: 'battery_below_75dc', label: 'Batería < 75V DC', flags: ['B.2.voltage_battery_below_75dc'] },
      { value: 'mixed', label: 'Tensión mixta / múltiples rangos', flags: ['B.2.voltage_mixed'] },
    ],
  },
  {
    id: 'B.3', block: 'B', type: 'single',
    label: '¿Tiene electrónica activa (procesador, microcontrolador, FPGA)?',
    visibleWhen: (flags) => flags.has('B.1.yes'),
    options: [
      { value: 'yes', label: 'Sí', flags: ['B.3.has_active_electronics'] },
      { value: 'no', label: 'No — solo componentes pasivos', flags: ['B.3.passive_only'] },
    ],
  },
  {
    id: 'B.4', block: 'B', type: 'multi',
    label: '¿Utiliza alguna tecnología de radio / comunicación inalámbrica?',
    visibleWhen: (flags) => flags.has('B.1.yes'),
    options: [
      { value: 'wifi', label: 'WiFi', flags: ['B.4.has_radio'] },
      { value: 'bluetooth', label: 'Bluetooth / BLE', flags: ['B.4.has_radio'] },
      { value: 'cellular', label: 'Celular (4G/5G/LTE)', flags: ['B.4.has_radio'] },
      { value: 'rfid', label: 'RFID / NFC', flags: ['B.4.has_radio'] },
      { value: 'lora', label: 'LoRa / Sigfox / LPWAN', flags: ['B.4.has_radio'] },
      { value: 'uwb', label: 'UWB', flags: ['B.4.has_radio'] },
      { value: 'other_radio', label: 'Otra tecnología de radio', flags: ['B.4.has_radio'] },
      { value: 'no_radio', label: 'No utiliza radio', flags: ['B.4.no_radio'] },
    ],
  },
  {
    id: 'B.4.a', block: 'B', type: 'single',
    label: '¿Es un equipo de radioaficionado no comercial?',
    visibleWhen: (flags) => flags.has('B.4.has_radio'),
    options: [
      { value: 'yes', label: 'Sí — radioaficionado no comercial', flags: ['B.4a.amateur_radio_non_commercial'] },
      { value: 'no', label: 'No — uso comercial / general', flags: ['B.4a.commercial_radio'] },
    ],
  },
  {
    id: 'B.5', block: 'B', type: 'multi',
    label: '¿El producto contiene baterías?',
    visibleWhen: (flags) => flags.has('B.1.yes'),
    options: [
      { value: 'li_ion', label: 'Sí — Li-ion / Li-Po', flags: ['B.5.has_battery'] },
      { value: 'lead_acid', label: 'Sí — Plomo-ácido', flags: ['B.5.has_battery'] },
      { value: 'nimh', label: 'Sí — NiMH / NiCd', flags: ['B.5.has_battery'] },
      { value: 'alkaline', label: 'Sí — Alcalinas / primarias', flags: ['B.5.has_battery'] },
      { value: 'other_chem', label: 'Sí — Otra química', flags: ['B.5.has_battery'] },
      { value: 'no', label: 'No contiene baterías', flags: ['B.5.no_battery'] },
    ],
  },
  {
    id: 'B.5.a', block: 'B', type: 'single',
    label: '¿Qué tipo de batería según la regulación EU?',
    visibleWhen: (flags) => flags.has('B.5.has_battery'),
    options: [
      { value: 'portable', label: 'Portátil (≤ 5 kg)', flags: ['B.5a.battery_portable'] },
      { value: 'lmt', label: 'LMT (medios de transporte ligeros)', flags: ['B.5a.battery_lmt'] },
      { value: 'sli', label: 'SLI (arranque/iluminación/encendido)', flags: ['B.5a.battery_sli'] },
      { value: 'industrial', label: 'Industrial (> 5 kWh)', flags: ['B.5a.battery_industrial'] },
      { value: 'ev', label: 'EV (vehículo eléctrico)', flags: ['B.5a.battery_ev'] },
      { value: 'military_space', label: 'Militar / espacial', flags: ['B.5a.battery_military_space'] },
    ],
  },
  {
    id: 'B.6', block: 'B', type: 'single',
    label: '¿El producto incorpora software o firmware?',
    visibleWhen: (flags) => flags.has('B.1.yes'),
    options: [
      { value: 'yes', label: 'Sí', flags: ['B.6.yes'] },
      { value: 'no', label: 'No', flags: ['B.6.no'] },
    ],
  },
  {
    id: 'B.6.a', block: 'B', type: 'single',
    label: '¿El software incluye componentes de inteligencia artificial?',
    visibleWhen: (flags) => flags.has('B.6.yes'),
    options: [
      { value: 'yes', label: 'Sí — tiene IA', flags: ['B.6a.yes'] },
      { value: 'no', label: 'No', flags: ['B.6a.no_ai'] },
    ],
  },
  {
    id: 'B.6.a.i', block: 'B', type: 'multi',
    label: '¿En qué categoría de alto riesgo se clasifica la IA?',
    visibleWhen: (flags) => flags.has('B.6a.yes'),
    options: [
      { value: 'biometric', label: 'Identificación biométrica', flags: ['B.6ai.biometric'] },
      { value: 'critical_infra', label: 'Infraestructura crítica', flags: ['B.6ai.critical_infrastructure'] },
      { value: 'education', label: 'Educación / formación', flags: ['B.6ai.education'] },
      { value: 'employment', label: 'Empleo / gestión de trabajadores', flags: ['B.6ai.employment'] },
      { value: 'essential', label: 'Servicios esenciales', flags: ['B.6ai.essential_services'] },
      { value: 'law_enforcement', label: 'Aplicación de la ley', flags: ['B.6ai.law_enforcement'] },
      { value: 'migration', label: 'Migración / control de fronteras', flags: ['B.6ai.migration'] },
      { value: 'justice', label: 'Justicia / procesos democráticos', flags: ['B.6ai.justice'] },
      { value: 'gpai', label: 'IA de propósito general (GPAI)', flags: ['B.6ai.general_purpose'] },
      { value: 'military', label: 'Exclusivamente defensa/militar', flags: ['B.6ai.military_defence_only'] },
    ],
  },
  {
    id: 'B.6.b', block: 'B', type: 'single',
    label: '¿El producto tiene conectividad de red (directa o indirecta)?',
    visibleWhen: (flags) => flags.has('B.6.yes'),
    options: [
      { value: 'always', label: 'Sí — siempre conectado', flags: ['B.6b.yes_always_connected'] },
      { value: 'occasionally', label: 'Sí — conexión ocasional', flags: ['B.6b.yes_occasionally'] },
      { value: 'pure_saas', label: 'Solo SaaS (sin producto físico)', flags: ['B.6b.pure_saas'] },
      { value: 'open_source', label: 'Open source no comercial', flags: ['B.6b.non_commercial_open_source'] },
      { value: 'no', label: 'No — funciona offline', flags: ['B.6b.no_connectivity'] },
    ],
  },

  // ── BLOCK C ──────────────────────────────────────────────
  {
    id: 'C.1', block: 'C', type: 'single',
    label: '¿El producto es una máquina o contiene partes móviles accionadas?',
    visibleWhen: null,
    options: [
      { value: 'yes', label: 'Sí', flags: ['C.1.yes'] },
      { value: 'no', label: 'No', flags: ['C.1.no'] },
    ],
  },
  {
    id: 'C.1.a', block: 'C', type: 'multi',
    label: '¿Qué tipo de maquinaria?',
    visibleWhen: (flags) => flags.has('C.1.yes'),
    options: [
      { value: 'complete', label: 'Máquina completa', flags: ['C.1a.complete_machine'] },
      { value: 'safety_component', label: 'Componente de seguridad', flags: ['C.1a.safety_component'] },
      { value: 'lifting', label: 'Accesorio de elevación', flags: ['C.1a.lifting_accessory'] },
      { value: 'chain_rope', label: 'Cadenas, cables, cinchas', flags: ['C.1a.chain_rope_webbing'] },
      { value: 'transmission', label: 'Dispositivo de transmisión desmontable', flags: ['C.1a.transmission_device'] },
      { value: 'partly', label: 'Cuasi-máquina (parcialmente completada)', flags: ['C.1a.partly_completed'] },
      { value: 'interchangeable', label: 'Equipo intercambiable', flags: ['C.1a.interchangeable_equipment'] },
      { value: 'agri_tractor', label: 'Tractor agrícola (excluido)', flags: ['C.1a.agricultural_tractor'] },
      { value: 'motor_vehicle', label: 'Vehículo de motor (excluido)', flags: ['C.1a.motor_vehicle'] },
      { value: 'fairground', label: 'Atracción de feria (excluido)', flags: ['C.1a.fairground_ride'] },
    ],
  },
  {
    id: 'C.2', block: 'C', type: 'single',
    label: '¿El producto opera con fluidos a presión?',
    visibleWhen: null,
    options: [
      { value: 'none', label: 'No — sin presión', flags: ['C.2.pressure_none'] },
      { value: 'below_0_5', label: 'Sí — pero < 0.5 bar', flags: ['C.2.pressure_below_0_5'] },
      { value: 'spvd', label: 'Sí — recipiente simple (SPVD: 0.5–30 bar, aire/N₂)', flags: ['C.2.pressure_spvd_range'] },
      { value: 'ped', label: 'Sí — equipo a presión (PED: > 0.5 bar, complejo)', flags: ['C.2.pressure_ped_range'] },
      { value: 'transportable', label: 'Sí — recipiente transportable (TPED)', flags: ['C.2.pressure_transportable'] },
    ],
  },
  {
    id: 'C.3', block: 'C', type: 'single',
    label: '¿El producto utiliza gas o combustible?',
    visibleWhen: null,
    options: [
      { value: 'yes', label: 'Sí', flags: ['C.3.yes'] },
      { value: 'no', label: 'No', flags: ['C.3.no'] },
    ],
  },
  {
    id: 'C.3.a', block: 'C', type: 'single',
    label: '¿Qué tipo de aparato de gas?',
    visibleWhen: (flags) => flags.has('C.3.yes'),
    options: [
      { value: 'domestic', label: 'Aparato doméstico/comercial (cocina, caldera)', flags: ['C.3a.domestic_commercial_appliance'] },
      { value: 'industrial', label: 'Proceso industrial', flags: ['C.3a.industrial_process'] },
      { value: 'marine_aircraft', label: 'Marina / aeronáutica', flags: ['C.3a.marine_aircraft'] },
      { value: 'outdoor', label: 'Barbacoa / exterior', flags: ['C.3a.outdoor_barbecue'] },
      { value: 'explosive_atm', label: 'Atmósfera explosiva', flags: ['C.3a.explosive_atmosphere'] },
    ],
  },

  // ── BLOCK D ──────────────────────────────────────────────
  {
    id: 'D.1', block: 'D', type: 'single',
    label: '¿El producto está relacionado con elevación o transporte por cable?',
    visibleWhen: null,
    options: [
      { value: 'vertical_lift', label: 'Ascensor / elevación vertical', flags: ['D.1.vertical_lift'] },
      { value: 'cableway', label: 'Instalación de transporte por cable', flags: ['D.1.cableway'] },
      { value: 'none', label: 'No aplica', flags: ['D.1.none'] },
    ],
  },
  {
    id: 'D.1.a', block: 'D', type: 'single',
    label: '¿Qué tipo de ascensor/elevación?',
    visibleWhen: (flags) => flags.has('D.1.vertical_lift'),
    options: [
      { value: 'passenger', label: 'Ascensor de personas', flags: ['D.1a.passenger_lift'] },
      { value: 'goods_fast', label: 'Montacargas accesible (> 0.15 m/s)', flags: ['D.1a.goods_lift_accessible_fast'] },
      { value: 'safety_comp', label: 'Componente de seguridad de ascensor', flags: ['D.1a.lift_safety_component'] },
      { value: 'goods_slow', label: 'Montacargas lento (≤ 0.15 m/s)', flags: ['D.1a.goods_lift_slow'] },
      { value: 'construction', label: 'Grúa / elevador de obra', flags: ['D.1a.construction_hoist'] },
      { value: 'escalator', label: 'Escalera mecánica / pasillo rodante', flags: ['D.1a.escalator_walkway'] },
    ],
  },
  {
    id: 'D.1.b', block: 'D', type: 'single',
    label: '¿Qué tipo de transporte por cable?',
    visibleWhen: (flags) => flags.has('D.1.cableway'),
    options: [
      { value: 'ski', label: 'Telesilla / telesquí', flags: ['D.1b.ski_chair_drag'] },
      { value: 'gondola', label: 'Telecabina / góndola', flags: ['D.1b.gondola_telecabine'] },
      { value: 'funicular', label: 'Funicular', flags: ['D.1b.funicular'] },
      { value: 'aerial', label: 'Teleférico', flags: ['D.1b.aerial_ropeway'] },
      { value: 'agri', label: 'Agrícola / forestal (excluido)', flags: ['D.1b.agricultural_forestry'] },
      { value: 'funfair', label: 'Feria / parque de atracciones (excluido)', flags: ['D.1b.funfair_amusement'] },
      { value: 'sport', label: 'Competición deportiva (excluido)', flags: ['D.1b.sport_racing'] },
    ],
  },

  // ── BLOCK E ──────────────────────────────────────────────
  {
    id: 'E.1', block: 'E', type: 'single',
    label: '¿El producto es un equipo de protección individual (EPI)?',
    visibleWhen: null,
    options: [
      { value: 'yes', label: 'Sí — lo lleva puesto una persona para protección', flags: ['E.1.worn_by_person'] },
      { value: 'no', label: 'No', flags: ['E.1.no'] },
    ],
  },
  {
    id: 'E.1.a', block: 'E', type: 'multi',
    label: '¿Contra qué riesgos protege?',
    visibleWhen: (flags) => flags.has('E.1.worn_by_person'),
    options: [
      { value: 'mechanical', label: 'Mecánicos (impacto, corte, vibración)', flags: ['E.1a.mechanical'] },
      { value: 'thermal', label: 'Térmicos (calor, frío)', flags: ['E.1a.thermal'] },
      { value: 'chemical', label: 'Químicos / biológicos', flags: ['E.1a.chemical_biological'] },
      { value: 'electrical', label: 'Eléctricos', flags: ['E.1a.electrical'] },
      { value: 'fall', label: 'Caída de altura', flags: ['E.1a.fall_height'] },
      { value: 'respiratory', label: 'Respiratorios', flags: ['E.1a.respiratory'] },
      { value: 'noise', label: 'Ruido / audición', flags: ['E.1a.noise_hearing'] },
      { value: 'radiation', label: 'Radiación', flags: ['E.1a.radiation'] },
      { value: 'drowning', label: 'Ahogamiento', flags: ['E.1a.drowning'] },
      { value: 'military_police', label: 'Militar / policial exclusivo', flags: ['E.1a.military_police_exclusive'] },
      { value: 'private', label: 'Uso privado (lluvia, fregar)', flags: ['E.1a.private_rain_dishwashing'] },
    ],
  },

  // ── BLOCK F ──────────────────────────────────────────────
  {
    id: 'F.1', block: 'F', type: 'single',
    label: '¿El producto se utilizará en atmósferas potencialmente explosivas?',
    visibleWhen: null,
    options: [
      { value: 'zone_0_20', label: 'Sí — Zona 0/20 (permanente)', flags: ['F.1.zone_0_20'] },
      { value: 'zone_1_21', label: 'Sí — Zona 1/21 (probable)', flags: ['F.1.zone_1_21'] },
      { value: 'zone_2_22', label: 'Sí — Zona 2/22 (ocasional)', flags: ['F.1.zone_2_22'] },
      { value: 'no', label: 'No', flags: ['F.1.no'] },
    ],
  },
  {
    id: 'F.2', block: 'F', type: 'multi',
    label: '¿El producto es un artículo pirotécnico o explosivo?',
    visibleWhen: null,
    options: [
      { value: 'none', label: 'No', flags: ['F.2.none'] },
      { value: 'firework_consumer', label: 'Fuegos artificiales — consumidor', flags: ['F.2.firework_consumer'] },
      { value: 'firework_professional', label: 'Fuegos artificiales — profesional', flags: ['F.2.firework_professional'] },
      { value: 'theatrical', label: 'Pirotecnia teatral', flags: ['F.2.theatrical_pyro'] },
      { value: 'airbag', label: 'Airbag / dispositivo de seguridad vehículo', flags: ['F.2.vehicle_airbag'] },
      { value: 'signal', label: 'Señal de socorro / bengala', flags: ['F.2.signal_flare'] },
      { value: 'blasting', label: 'Explosivo de voladura', flags: ['F.2.blasting_explosive'] },
      { value: 'detonator', label: 'Detonador', flags: ['F.2.detonator'] },
      { value: 'det_cord', label: 'Cordón detonante', flags: ['F.2.detonating_cord'] },
      { value: 'military_police', label: 'Uso militar/policial', flags: ['F.2.military_police_use'] },
      { value: 'percussion_toy', label: 'Pistón de percusión para juguete', flags: ['F.2.percussion_cap_toy'] },
      { value: 'aerospace', label: 'Pirotecnia aeroespacial', flags: ['F.2.aerospace_pyro'] },
    ],
  },

  // ── BLOCK G ──────────────────────────────────────────────
  {
    id: 'G.1', block: 'G', type: 'single',
    label: '¿El producto es un vehículo, embarcación o aeronave no tripulada?',
    visibleWhen: null,
    options: [
      { value: 'commercial_ship', label: 'Equipo marino (buque comercial)', flags: ['G.1.commercial_ship'] },
      { value: 'recreational', label: 'Embarcación de recreo', flags: ['G.1.recreational_watercraft'] },
      { value: 'drone', label: 'Dron / UAS', flags: ['G.1.drone'] },
      { value: 'none', label: 'Ninguno de los anteriores', flags: ['G.1.none'] },
    ],
  },
  {
    id: 'G.1.a', block: 'G', type: 'multi',
    label: '¿Qué tipo de equipo marino?',
    visibleWhen: (flags) => flags.has('G.1.commercial_ship'),
    options: [
      { value: 'lifesaving', label: 'Salvamento', flags: ['G.1a.lifesaving'] },
      { value: 'fire', label: 'Protección contra incendios', flags: ['G.1a.fire_protection'] },
      { value: 'navigation', label: 'Navegación', flags: ['G.1a.navigation'] },
      { value: 'communication', label: 'Comunicaciones', flags: ['G.1a.communication'] },
      { value: 'pollution', label: 'Prevención de contaminación', flags: ['G.1a.pollution_prevention'] },
      { value: 'marine_equip', label: 'Equipo MED general', flags: ['G.1a.marine_equipment'] },
    ],
  },
  {
    id: 'G.1.b', block: 'G', type: 'single',
    label: '¿Qué tipo de embarcación de recreo?',
    visibleWhen: (flags) => flags.has('G.1.recreational_watercraft'),
    options: [
      { value: 'motorboat', label: 'Lancha / yate a motor (2.5–24m)', flags: ['G.1b.motorboat_yacht'] },
      { value: 'pwc', label: 'Moto acuática', flags: ['G.1b.personal_watercraft'] },
      { value: 'racing', label: 'Embarcación de competición', flags: ['G.1b.racing_watercraft'] },
      { value: 'canoe', label: 'Canoa / kayak / patín', flags: ['G.1b.canoe_kayak_pedalo'] },
      { value: 'surfboard', label: 'Tabla de surf', flags: ['G.1b.surfboard'] },
      { value: 'historic', label: 'Histórica (pre-1950)', flags: ['G.1b.historic_pre1950'] },
      { value: 'submersible', label: 'Sumergible / hidroala', flags: ['G.1b.submersible_hydrofoil'] },
    ],
  },
  {
    id: 'G.1.c', block: 'G', type: 'single',
    label: '¿Clase del dron (UAS)?',
    visibleWhen: (flags) => flags.has('G.1.drone'),
    options: [
      { value: 'c0', label: 'Clase C0 (< 250g)', flags: ['G.1c.class_C0'] },
      { value: 'c1', label: 'Clase C1 (< 900g)', flags: ['G.1c.class_C1'] },
      { value: 'c2', label: 'Clase C2 (< 4kg)', flags: ['G.1c.class_C2'] },
      { value: 'c3', label: 'Clase C3 (< 25kg)', flags: ['G.1c.class_C3'] },
      { value: 'c4', label: 'Clase C4 (< 25kg, sin auto)', flags: ['G.1c.class_C4'] },
      { value: 'c5_c6', label: 'Clase C5/C6 (específica)', flags: ['G.1c.class_C5_C6'] },
      { value: 'military', label: 'Militar / estatal', flags: ['G.1c.military_state'] },
      { value: 'model', label: 'Aeromodelismo (club)', flags: ['G.1c.model_aircraft_club_only'] },
    ],
  },

  // ── BLOCK H ──────────────────────────────────────────────
  {
    id: 'H.1', block: 'H', type: 'single',
    label: '¿El producto tiene finalidad médica o diagnóstica?',
    visibleWhen: null,
    options: [
      { value: 'medical', label: 'Sí — diagnóstico, tratamiento o monitorización médica', flags: ['H.1.medical_condition'] },
      { value: 'annex_xvi', label: 'Sí — estético (Anexo XVI MDR)', flags: ['H.1.annex_xvi_aesthetic'] },
      { value: 'ivd', label: 'Sí — diagnóstico in vitro (IVD)', flags: ['H.1.ivd_device'] },
      { value: 'wellness', label: 'Solo bienestar general (no médico)', flags: ['H.1.general_wellness'] },
      { value: 'no', label: 'No — sin finalidad médica', flags: ['H.1.no'] },
    ],
  },
  {
    id: 'H.1.a', block: 'H', type: 'single',
    label: '¿Es un dispositivo médico activo implantable?',
    visibleWhen: (flags) => flags.has('H.1.medical_condition'),
    options: [
      { value: 'yes', label: 'Sí', flags: ['H.1a.medical_device'] },
      { value: 'no', label: 'No — dispositivo médico no implantable', flags: ['H.1a.non_implantable'] },
    ],
  },
  {
    id: 'H.1.b', block: 'H', type: 'single',
    label: '¿Qué tipo de IVD?',
    visibleWhen: (flags) => flags.has('H.1.ivd_device'),
    options: [
      { value: 'reagent', label: 'Kit de reactivos', flags: ['H.1b.reagent_kit'] },
      { value: 'analyser', label: 'Analizador de laboratorio', flags: ['H.1b.lab_analyser'] },
      { value: 'poc', label: 'Point-of-care / autodiagnóstico', flags: ['H.1b.point_of_care'] },
      { value: 'genetic', label: 'Genético / molecular', flags: ['H.1b.genetic_molecular'] },
      { value: 'general_lab', label: 'Laboratorio general (sin intención IVD)', flags: ['H.1b.general_lab_no_ivd_intent'] },
      { value: 'invasive', label: 'Muestreo invasivo', flags: ['H.1b.invasive_sampling'] },
    ],
  },

  // ── BLOCK I ──────────────────────────────────────────────
  {
    id: 'I.1', block: 'I', type: 'single',
    label: '¿El producto es un instrumento de medida o pesaje?',
    visibleWhen: null,
    options: [
      { value: 'yes', label: 'Sí', flags: ['I.1.yes'] },
      { value: 'no', label: 'No', flags: ['I.1.no'] },
    ],
  },
  {
    id: 'I.1.a', block: 'I', type: 'multi',
    label: '¿Qué tipo de instrumento?',
    visibleWhen: (flags) => flags.has('I.1.yes'),
    options: [
      { value: 'nawi_commercial', label: 'Balanza no automática — comercial', flags: ['I.1a.non_auto_weighing_commercial'] },
      { value: 'nawi_medical', label: 'Balanza no automática — médica', flags: ['I.1a.non_auto_weighing_medical'] },
      { value: 'nawi_pharma', label: 'Balanza no automática — farmacéutica', flags: ['I.1a.non_auto_weighing_pharma'] },
      { value: 'nawi_legal', label: 'Balanza no automática — metrología legal', flags: ['I.1a.non_auto_weighing_legal'] },
      { value: 'water', label: 'Contador de agua', flags: ['I.1a.water_volume'] },
      { value: 'gas', label: 'Contador de gas', flags: ['I.1a.gas_volume'] },
      { value: 'electrical', label: 'Contador de energía eléctrica', flags: ['I.1a.electrical_energy'] },
      { value: 'thermal', label: 'Contador de energía térmica', flags: ['I.1a.thermal_energy'] },
      { value: 'liquid', label: 'Medidor de flujo de líquidos', flags: ['I.1a.liquid_flow'] },
      { value: 'auto_weighing', label: 'Pesaje automático', flags: ['I.1a.automatic_weighing'] },
      { value: 'taximeter', label: 'Taxímetro', flags: ['I.1a.taximeter'] },
      { value: 'length', label: 'Medidor de longitud / materiales', flags: ['I.1a.length_materials'] },
      { value: 'dimensional', label: 'Medición dimensional', flags: ['I.1a.dimensional'] },
      { value: 'exhaust', label: 'Analizador de gases de escape', flags: ['I.1a.exhaust_gas'] },
      { value: 'domestic', label: 'Solo uso doméstico', flags: ['I.1a.weighing_domestic_only'] },
    ],
  },

  // ── BLOCK J ──────────────────────────────────────────────
  {
    id: 'J.1', block: 'J', type: 'single',
    label: '¿El producto es un artículo físico comercializado en la EU?',
    visibleWhen: null,
    options: [
      { value: 'yes', label: 'Sí', flags: ['J.1.yes'] },
      { value: 'no', label: 'No', flags: ['J.1.no'] },
    ],
  },
  {
    id: 'J.1.a', block: 'J', type: 'multi',
    label: '¿Alguna de estas exclusiones ESPR aplica?',
    visibleWhen: (flags) => flags.has('J.1.yes'),
    options: [
      { value: 'none', label: 'Ninguna exclusión aplica', flags: [] },
      { value: 'food_feed', label: 'Alimento o pienso', flags: ['J.1a.food_feed'] },
      { value: 'medicinal', label: 'Medicamento (humano o veterinario)', flags: ['J.1a.medicinal_veterinary'] },
      { value: 'motor_vehicle', label: 'Vehículo de motor', flags: ['J.1a.motor_vehicle'] },
      { value: 'defence', label: 'Defensa / seguridad', flags: ['J.1a.defence_security'] },
      { value: 'rohs_industrial', label: 'Instalación industrial a gran escala (RoHS)', flags: ['J.1a.rohs_large_scale_industrial'] },
      { value: 'rohs_implant', label: 'Implante activo (RoHS)', flags: ['J.1a.rohs_active_implantable'] },
      { value: 'rohs_pv', label: 'Panel fotovoltaico (RoHS)', flags: ['J.1a.rohs_photovoltaic'] },
      { value: 'rohs_organ', label: 'Órgano de tubos (RoHS)', flags: ['J.1a.rohs_pipe_organ'] },
    ],
  },
  {
    id: 'J.2', block: 'J', type: 'multi',
    label: '¿El producto incluye embalaje/packaging?',
    visibleWhen: null,
    options: [
      { value: 'none', label: 'Sin embalaje regulado', flags: ['J.2.none'] },
      { value: 'consumer', label: 'Embalaje de consumo', flags: ['J.2.consumer_packaging'] },
      { value: 'industrial', label: 'Embalaje industrial / transporte', flags: ['J.2.industrial_transport_packaging'] },
      { value: 'ecommerce', label: 'Embalaje e-commerce', flags: ['J.2.ecommerce_packaging'] },
      { value: 'dangerous', label: 'Solo transporte de mercancías peligrosas', flags: ['J.2.dangerous_goods_transport_only'] },
    ],
  },

  // ── BLOCK K ──────────────────────────────────────────────
  {
    id: 'K.1', block: 'K', type: 'single',
    label: '¿El producto se incorpora permanentemente en obras de construcción?',
    visibleWhen: (flags) => flags.has('A.1.construction'),
    options: [
      { value: 'yes', label: 'Sí', flags: ['K.1.yes'] },
      { value: 'no', label: 'No', flags: ['K.1.no'] },
    ],
  },
  {
    id: 'K.1.a', block: 'K', type: 'single',
    label: '¿Existe norma armonizada publicada para este producto de construcción?',
    visibleWhen: (flags) => flags.has('K.1.yes'),
    options: [
      { value: 'yes', label: 'Sí — norma armonizada publicada', flags: ['K.1a.harmonised_standard_yes'] },
      { value: 'no', label: 'No — sin norma armonizada', flags: ['K.1a.harmonised_standard_no'] },
    ],
  },
];

// ── 30 NLF Legislations ──────────────────────────────────────────
const LEGISLATIONS = [
  { id: 1, code: 'Toy Safety', ref: '(EU) 2025/2509', name: 'Reglamento de Seguridad de Juguetes',
    trigger_keys: ['A.1.a.yes_play_value'],
    exclusion_keys: ['A.1.a.no_no_play_value', 'A.3.military_exclusive', 'A.3.space_exclusive'] },
  { id: 2, code: 'TPED', ref: '2010/35/EU', name: 'Directiva de Equipos a Presión Transportables',
    trigger_keys: ['C.2.pressure_transportable'],
    exclusion_keys: ['A.3.military_exclusive', 'A.3.space_exclusive'] },
  { id: 3, code: 'RoHS', ref: '2011/65/EU', name: 'Restricción de Sustancias Peligrosas',
    trigger_keys: ['B.1.yes'],
    exclusion_keys: ['J.1a.rohs_large_scale_industrial', 'J.1a.rohs_active_implantable', 'J.1a.rohs_photovoltaic', 'J.1a.rohs_pipe_organ', 'A.3.military_exclusive', 'A.3.space_exclusive'] },
  { id: 4, code: 'CPR', ref: '(EU) 305/2011', name: 'Reglamento de Productos de Construcción',
    trigger_keys: ['K.1.yes', 'K.1a.harmonised_standard_yes'],
    exclusion_keys: ['K.1a.harmonised_standard_no'] },
  { id: 5, code: 'Pyrotechnics', ref: '2013/29/EU', name: 'Directiva de Artículos Pirotécnicos',
    trigger_keys: ['F.2.firework_consumer', 'F.2.firework_professional', 'F.2.theatrical_pyro', 'F.2.vehicle_airbag', 'F.2.signal_flare'],
    exclusion_keys: ['F.2.military_police_use', 'F.2.percussion_cap_toy', 'F.2.aerospace_pyro'] },
  { id: 6, code: 'RCD', ref: '2013/53/EU', name: 'Directiva de Embarcaciones de Recreo',
    trigger_keys: ['G.1b.motorboat_yacht', 'G.1b.personal_watercraft'],
    exclusion_keys: ['G.1b.racing_watercraft', 'G.1b.canoe_kayak_pedalo', 'G.1b.surfboard', 'G.1b.historic_pre1950', 'G.1b.submersible_hydrofoil'] },
  { id: 7, code: 'Civil Explosives', ref: '2014/28/EU', name: 'Directiva de Explosivos Civiles',
    trigger_keys: ['F.2.blasting_explosive', 'F.2.detonator', 'F.2.detonating_cord'],
    exclusion_keys: ['F.2.military_police_use'] },
  { id: 8, code: 'SPVD', ref: '2014/29/EU', name: 'Directiva de Recipientes a Presión Simples',
    trigger_keys: ['C.2.pressure_spvd_range'],
    exclusion_keys: ['C.2.pressure_none', 'C.2.pressure_below_0_5'] },
  { id: 9, code: 'EMC', ref: '2014/30/EU', name: 'Directiva de Compatibilidad Electromagnética',
    trigger_keys: ['B.3.has_active_electronics'],
    exclusion_keys: ['B.4.has_radio', 'H.1a.medical_device', 'A.3.military_exclusive'] },
  { id: 10, code: 'NAWID', ref: '2014/31/EU', name: 'Directiva de Instrumentos de Pesaje No Automáticos',
    trigger_keys: ['I.1a.non_auto_weighing_commercial', 'I.1a.non_auto_weighing_medical', 'I.1a.non_auto_weighing_pharma', 'I.1a.non_auto_weighing_legal'],
    exclusion_keys: ['I.1a.weighing_domestic_only'] },
  { id: 11, code: 'MID', ref: '2014/32/EU', name: 'Directiva de Instrumentos de Medida',
    trigger_keys: ['I.1a.water_volume', 'I.1a.gas_volume', 'I.1a.electrical_energy', 'I.1a.thermal_energy', 'I.1a.liquid_flow', 'I.1a.automatic_weighing', 'I.1a.taximeter', 'I.1a.length_materials', 'I.1a.dimensional', 'I.1a.exhaust_gas'],
    exclusion_keys: ['I.1a.weighing_domestic_only'] },
  { id: 12, code: 'Lifts', ref: '2014/33/EU', name: 'Directiva de Ascensores',
    trigger_keys: ['D.1a.passenger_lift', 'D.1a.goods_lift_accessible_fast', 'D.1a.lift_safety_component'],
    exclusion_keys: ['D.1a.goods_lift_slow', 'D.1a.construction_hoist', 'D.1a.escalator_walkway'] },
  { id: 13, code: 'ATEX', ref: '2014/34/EU', name: 'Directiva ATEX (Atmósferas Explosivas)',
    trigger_keys: ['F.1.zone_0_20', 'F.1.zone_1_21', 'F.1.zone_2_22'],
    exclusion_keys: ['A.3.military_exclusive', 'H.1.medical_condition'] },
  { id: 14, code: 'RED', ref: '2014/53/EU', name: 'Directiva de Equipos de Radio',
    trigger_keys: ['B.4.has_radio'],
    exclusion_keys: ['G.1a.marine_equipment', 'A.3.space_exclusive', 'B.4a.amateur_radio_non_commercial'] },
  { id: 15, code: 'LVD', ref: '2014/35/EU', name: 'Directiva de Baja Tensión',
    trigger_keys: ['B.2.voltage_50_1000_ac', 'B.2.voltage_75_1500_dc', 'B.2.voltage_mains_230', 'B.2.voltage_mains_400', 'B.2.voltage_battery_above_75dc', 'B.2.voltage_mixed'],
    exclusion_keys: ['B.2.voltage_below_50ac_75dc', 'B.2.voltage_battery_below_75dc', 'F.1.zone_0_20', 'H.1a.medical_device', 'A.3.military_exclusive'] },
  { id: 16, code: 'PED', ref: '2014/68/EU', name: 'Directiva de Equipos a Presión',
    trigger_keys: ['C.2.pressure_ped_range'],
    exclusion_keys: ['C.2.pressure_none', 'C.2.pressure_below_0_5', 'C.2.pressure_spvd_range', 'C.2.pressure_transportable'] },
  { id: 17, code: 'MED', ref: '2014/90/EU', name: 'Directiva de Equipamiento Marino',
    trigger_keys: ['G.1a.lifesaving', 'G.1a.fire_protection', 'G.1a.navigation', 'G.1a.communication', 'G.1a.pollution_prevention'],
    exclusion_keys: ['G.1b.motorboat_yacht', 'A.3.military_exclusive'] },
  { id: 18, code: 'Cableways', ref: '(EU) 2016/424', name: 'Reglamento de Instalaciones de Teleféricos',
    trigger_keys: ['D.1b.ski_chair_drag', 'D.1b.gondola_telecabine', 'D.1b.funicular', 'D.1b.aerial_ropeway'],
    exclusion_keys: ['D.1b.agricultural_forestry', 'D.1b.funfair_amusement', 'D.1b.sport_racing'] },
  { id: 19, code: 'PPE', ref: '(EU) 2016/425', name: 'Reglamento de Equipos de Protección Individual',
    trigger_keys: ['E.1a.mechanical', 'E.1a.thermal', 'E.1a.chemical_biological', 'E.1a.electrical', 'E.1a.fall_height', 'E.1a.respiratory', 'E.1a.noise_hearing', 'E.1a.radiation', 'E.1a.drowning'],
    exclusion_keys: ['E.1a.military_police_exclusive', 'E.1a.private_rain_dishwashing'] },
  { id: 20, code: 'GAR', ref: '(EU) 2016/426', name: 'Reglamento de Aparatos de Gas',
    trigger_keys: ['C.3a.domestic_commercial_appliance'],
    exclusion_keys: ['C.3a.industrial_process', 'C.3a.marine_aircraft', 'C.3a.outdoor_barbecue', 'C.3a.explosive_atmosphere'] },
  { id: 21, code: 'MDR', ref: '(EU) 2017/745', name: 'Reglamento de Dispositivos Médicos',
    trigger_keys: ['H.1.medical_condition', 'H.1.annex_xvi_aesthetic'],
    exclusion_keys: ['H.1b.ivd_device', 'H.1.general_wellness'] },
  { id: 22, code: 'IVDR', ref: '(EU) 2017/746', name: 'Reglamento de Diagnóstico In Vitro',
    trigger_keys: ['H.1b.reagent_kit', 'H.1b.lab_analyser', 'H.1b.point_of_care', 'H.1b.genetic_molecular'],
    exclusion_keys: ['H.1b.general_lab_no_ivd_intent', 'H.1b.invasive_sampling'] },
  { id: 23, code: 'FPR', ref: '(EU) 2019/1009', name: 'Reglamento de Productos Fertilizantes',
    trigger_keys: ['A.1.fertiliser_biostimulant'],
    exclusion_keys: ['A.3.military_exclusive'] },
  { id: 24, code: 'UAS', ref: '(EU) 2019/945', name: 'Reglamento de Drones (UAS)',
    trigger_keys: ['G.1c.class_C0', 'G.1c.class_C1', 'G.1c.class_C2', 'G.1c.class_C3', 'G.1c.class_C4', 'G.1c.class_C5_C6'],
    exclusion_keys: ['G.1c.military_state', 'G.1c.model_aircraft_club_only'] },
  { id: 25, code: 'Batteries', ref: '(EU) 2023/1542', name: 'Reglamento de Baterías',
    trigger_keys: ['B.5a.battery_portable', 'B.5a.battery_lmt', 'B.5a.battery_sli', 'B.5a.battery_industrial', 'B.5a.battery_ev'],
    exclusion_keys: ['B.5a.battery_military_space'] },
  { id: 26, code: 'Machinery', ref: '(EU) 2023/1230', name: 'Reglamento de Máquinas',
    trigger_keys: ['C.1.yes', 'C.1a.complete_machine', 'C.1a.safety_component', 'C.1a.lifting_accessory', 'C.1a.chain_rope_webbing', 'C.1a.transmission_device', 'C.1a.partly_completed', 'C.1a.interchangeable_equipment'],
    exclusion_keys: ['C.1a.agricultural_tractor', 'C.1a.motor_vehicle', 'C.1a.fairground_ride', 'A.3.military_exclusive'] },
  { id: 27, code: 'ESPR', ref: '(EU) 2024/1781', name: 'Reglamento de Ecodiseño (ESPR)',
    trigger_keys: ['J.1.yes'],
    exclusion_keys: ['J.1a.food_feed', 'J.1a.medicinal_veterinary', 'J.1a.motor_vehicle', 'J.1a.defence_security', 'A.4.exclusively_outside_eu'] },
  { id: 28, code: 'AI Act', ref: '(EU) 2024/1689', name: 'Reglamento de Inteligencia Artificial',
    trigger_keys: ['B.6a.yes', 'B.6ai.biometric', 'B.6ai.critical_infrastructure', 'B.6ai.education', 'B.6ai.employment', 'B.6ai.essential_services', 'B.6ai.law_enforcement', 'B.6ai.migration', 'B.6ai.justice', 'B.6ai.general_purpose'],
    exclusion_keys: ['B.6ai.military_defence_only', 'A.4.exclusively_outside_eu'] },
  { id: 29, code: 'CRA', ref: '(EU) 2024/2847', name: 'Ley de Ciberresiliencia',
    trigger_keys: ['B.6b.yes_always_connected', 'B.6b.yes_occasionally'],
    exclusion_keys: ['H.1.medical_condition', 'C.1a.motor_vehicle', 'B.6b.pure_saas', 'B.6b.non_commercial_open_source', 'A.3.military_exclusive'] },
  { id: 30, code: 'PPWR', ref: '(EU) 2025/40', name: 'Reglamento de Envases y Residuos de Envases',
    trigger_keys: ['J.2.consumer_packaging', 'J.2.industrial_transport_packaging', 'J.2.ecommerce_packaging'],
    exclusion_keys: ['J.2.dangerous_goods_transport_only', 'A.4.exclusively_outside_eu'] },
];

// Mutual exclusion rules
const MUTUAL_EXCLUSIONS = [
  { if_flag: 'C.2.pressure_spvd_range', exclude_ids: [16, 2] },
  { if_flag: 'C.2.pressure_ped_range', exclude_ids: [8, 2] },
  { if_flag: 'C.2.pressure_transportable', exclude_ids: [8, 16] },
  { if_flag: 'D.1a.goods_lift_slow', exclude_ids: [12], trigger_ids: [26] },
];

window.BLOCKS = BLOCKS;
window.QUESTIONS = QUESTIONS;
window.LEGISLATIONS = LEGISLATIONS;
window.MUTUAL_EXCLUSIONS = MUTUAL_EXCLUSIONS;
