/**
 * Nexo subdomain auth gate — verifying half.          GATE MIDDLEWARE v1.0.0
 * Written the 22.09.2026
 *
 * CANONICAL SOURCE: nexo-frontend/docs/gate-middleware/middleware.ts
 * Do not edit this file in a subdomain repo. Change the canonical copy, bump
 * the version above, and re-copy. See the README next to it.
 *
 * ── What it does ────────────────────────────────────────────────────────────
 * A gated subdomain is a static site with no session of its own. This refuses
 * to serve anything until the browser holds a signed session cookie, and sends
 * visitors to nexodesign.ai to get one:
 *
 *   no cookie  →  302 <issuer>/api/auth/gate?next=<what they asked for>
 *                 (the issuer checks the Supabase session, logging them in if
 *                  needed, and bounces back with a 60-second ticket)
 *   /__gate/callback?ticket=…  →  verify, Set-Cookie, 302 to where they were
 *   valid cookie  →  fall through, serve the file
 *
 * ── Two things to keep in mind when changing it ─────────────────────────────
 * 1. NO DEPENDENCIES. Returning `undefined` continues the chain, which is why
 *    this needs neither `@vercel/functions` nor a build step. HMAC is done with
 *    Web Crypto for the same reason.
 * 2. THE MATCHER COSTS MONEY. Middleware is billed per invocation and the
 *    matcher is applied before the function is invoked, so anything listed as
 *    an exception below is genuinely free. Exclude everything that is already
 *    public (vendor libraries, logos); gate everything that is yours.
 * 
 * IMPORTANT: Many below functions must be the same as gate.ts in the frontend, to match cookie
 * generation and validation. If gate.ts changes, this file needs to change also for ALL subdomains
 */

// ─── Configuration ────────────────────────────────────────────────────────────

/** Shared with the issuer. Same value in nexo-frontend and here. */
const SECRET = process.env.GATE_TICKET_SECRET
/** Where the login and the ticket issuer live, e.g. https://nexodesign.ai */
const ISSUER = process.env.GATE_ISSUER_URL
/** This site's own origin, e.g. https://editor.nexodesign.ai — taken from the
 *  environment rather than the request, so a forged Host header cannot make a
 *  ticket minted for another subdomain look like it was minted for this one. */
const SELF = process.env.GATE_SELF_ORIGIN

const COOKIE_NAME = 'nexo_gate'
const CALLBACK_PATH = '/__gate/callback'
const SESSION_TTL_SECONDS = 60 * 60

/**
 * Per-site: what the gate does NOT run on. Each exception is an invocation
 * saved on every page load, so list anything already public — but nothing of
 * your own, or it stays downloadable by anyone.
 */
export const config = {
  matcher: ['/((?!lib/|_vercel/|favicon\\.ico|nexodesign_logo\\.jpg).*)'],
}

// ─── HS256 over Web Crypto ────────────────────────────────────────────────────

function b64url(input: string | Uint8Array): string {
  const bytes = typeof input === 'string' ? new TextEncoder().encode(input) : input
  let binary = ''
  for (const byte of bytes) binary += String.fromCharCode(byte)
  return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '')
}

/** Returns an ArrayBuffer rather than a Uint8Array: both consumers below want
 *  a BufferSource, and the view's generic buffer type does not satisfy it. */
function b64urlDecode(value: string): ArrayBuffer {
  const padding = value.length % 4 === 0 ? '' : '='.repeat(4 - (value.length % 4))
  const binary = atob(value.replace(/-/g, '+').replace(/_/g, '/') + padding)
  const buffer = new ArrayBuffer(binary.length)
  const bytes = new Uint8Array(buffer)
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i)
  return buffer
}

function hmacKey(secret: string): Promise<CryptoKey> {
  return crypto.subtle.importKey(
    'raw',
    new TextEncoder().encode(secret),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign', 'verify']
  )
}

async function signJwt(payload: Record<string, unknown>, secret: string): Promise<string> {
  const head = b64url(JSON.stringify({ alg: 'HS256', typ: 'JWT' }))
  const body = b64url(JSON.stringify(payload))
  const signed = `${head}.${body}`
  const signature = await crypto.subtle.sign(
    'HMAC',
    await hmacKey(secret),
    new TextEncoder().encode(signed)
  )
  return `${signed}.${b64url(new Uint8Array(signature))}`
}

/** Payload if signature, expiry AND audience all check out; null otherwise. */
async function verifyJwt(
  token: string,
  secret: string,
  audience: string
): Promise<Record<string, unknown> | null> {
  const parts = token.split('.')
  if (parts.length !== 3) return null

  try {
    // crypto.subtle.verify compares in constant time.
    const ok = await crypto.subtle.verify(
      'HMAC',
      await hmacKey(secret),
      b64urlDecode(parts[2]),
      new TextEncoder().encode(`${parts[0]}.${parts[1]}`)
    )
    if (!ok) return null

    const payload = JSON.parse(new TextDecoder().decode(b64urlDecode(parts[1])))
    if (typeof payload.exp !== 'number' || payload.exp * 1000 <= Date.now()) return null
    // A ticket for another subdomain is not a ticket for this one.
    if (payload.aud !== audience) return null
    return payload
  } catch {
    return null
  }
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function readCookie(request: Request, name: string): string | null {
  const header = request.headers.get('cookie')
  if (!header) return null
  for (const part of header.split(';')) {
    const [key, ...rest] = part.trim().split('=')
    if (key === name) return rest.join('=')
  }
  return null
}

/** Relative paths only — a `next` is never allowed to point at another site. */
function safePath(value: string | null): string {
  if (!value || !value.startsWith('/') || value.startsWith('//') || value.includes('\\')) {
    return '/'
  }
  return value
}

function deniedPage(issuer: string): Response {
  // Deliberately NOT a redirect. A bad ticket arriving here means something is
  // wrong with the loop itself, and bouncing back to the issuer would spin.
  return new Response(
    `<!doctype html><meta charset="utf-8"><title>Sign-in needed</title>
     <body style="font:16px/1.6 system-ui;margin:4rem auto;max-width:32rem;padding:0 1rem">
     <h1 style="font-size:1.25rem">This sign-in link has expired</h1>
     <p>Open the tool again from Nexo Design and it will let you straight in.</p>
     <p><a href="${issuer}">Go to Nexo Design</a></p>`,
    { status: 401, headers: { 'content-type': 'text/html; charset=utf-8', 'cache-control': 'no-store' } }
  )
}

// ─── The gate ─────────────────────────────────────────────────────────────────

export default async function middleware(request: Request): Promise<Response | undefined> {
  if (!SECRET || !ISSUER || !SELF) {
    console.error('[gate] GATE_TICKET_SECRET / GATE_ISSUER_URL / GATE_SELF_ORIGIN missing')
    return new Response('Auth gate is not configured', { status: 500 })
  }

  const url = new URL(request.url)

  // Spending a ticket for a session cookie.
  if (url.pathname === CALLBACK_PATH) {
    const ticket = url.searchParams.get('ticket')
    const payload = ticket ? await verifyJwt(ticket, SECRET, SELF) : null
    if (!payload) return deniedPage(ISSUER)

    const now = Math.floor(Date.now() / 1000)
    const session = await signJwt(
      { sub: payload.sub, email: payload.email, aud: SELF, iat: now, exp: now + SESSION_TTL_SECONDS },
      SECRET
    )

    return new Response(null, {
      status: 302,
      headers: {
        location: safePath(url.searchParams.get('next')),
        // Host-only (no Domain=): this session stays on this subdomain and is
        // never readable by its siblings. SameSite=Lax is enough because the
        // subdomain shares a registrable domain with the dashboard that frames
        // it, so the cookie still travels inside that iframe.
        'set-cookie': `${COOKIE_NAME}=${session}; Path=/; Max-Age=${SESSION_TTL_SECONDS}; HttpOnly; Secure; SameSite=Lax`,
        'cache-control': 'no-store',
      },
    })
  }

  // Already holding a session → serve the file. Returning nothing continues
  // the chain; this is the hot path and it costs one HMAC verify.
  const cookie = readCookie(request, COOKIE_NAME)
  if (cookie && (await verifyJwt(cookie, SECRET, SELF))) return undefined

  // Otherwise go and get one. The issuer re-checks the Supabase session, so an
  // expired cookie on a still-signed-in user comes straight back with no login
  // form — that is the silent hourly renewal.
  const gate = new URL('/api/auth/gate', ISSUER)
  gate.searchParams.set('next', `${SELF}${url.pathname}${url.search}`)
  return new Response(null, {
    status: 302,
    headers: { location: gate.toString(), 'cache-control': 'no-store' },
  })
}
